baseURL = "https://www.supcik.net/"
theme = "introduction"
DefaultContentLanguage = "en"
disqusshortname = "supcik"
googleAnalytics = "UA-49403333-1"
publishdir = "public"
title = "Jacques Supcik"

# enforce_ssl = true
# builddrafts = false
# 
# canonifyurls = true
# layoutdir = "layouts"

pygmentsStyle = "monokailight"

[params]
    themeStyle = "light"
    favicon                      = "/img/profile.png"
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = false                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    
    dateFormat                   = "Jan 2, 2006"
    timeZone                     = "Europe/Zurich"         # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    timeFormat                   = "h:mm A"                 # https://momentjs.com/docs/#/displaying/format/

    email                        = "jacques@supcik.net"
    customCSS                    = ["supcik.css"]

    [params.home]
        introHeight              = "large"                 # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = true                    # Show your current local time in contact section
        timeRefresh              = 1000

    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

#     author = "Jacques Supcik"
#     firstname = "Jacques"
#     avatar = "img/profile.png" # Path to image in static folder eg. img/avatar.png, or comment out to remove
#     cachebuster = true # Add the current unix timestamp in query string for cache busting css assets
# 
#     showblog = true # Show Blog section on home page
#     showallposts = false # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
#     showlatest = true # Show latest blog post summary
#     showprojects    = false # Show Projects section on home page


    [params.share]
        twitter                  = true
        facebook                 = true
        googlePlus               = true
        pinterest                = true

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url = "https://github.com/supcik"
        icon = "github"
        icon_pack = "fab"
    [[params.social]]
        url = "https://gitlab.com/supcik"
        icon = "gitlab"
        icon_pack = "fab"
    [[params.social]]
        url = "https://plus.google.com/u/0/+JacquesSupcik"
        icon = "google-plus"
        icon_pack = "fab"
    [[params.social]]
        url = "https://twitter.com/supcik"
        icon = "twitter"
        icon_pack = "fab"
    [[params.social]]
        url = "https://facebook.com/jacques.supcik"
        icon = "facebook"
        icon_pack = "fab"
    [[params.social]]
        url = "https://www.linkedin.com/in/supcik/"
        icon = "linkedin"
        icon_pack = "fab"
    [[params.social]]
        url = "http://telegram.me/supcik"
        icon = "telegram"
        icon_pack = "fab"

[taxonomies]
  tag = "tags"

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        weight           = 1
        [languages.en.params]
            description  = "Personal web site of Jacques Supcik"   # Max 160 characters show in search results
            footerText   = ""

    [languages.fr]
        languageName     = "Français"
        languageCode     = "fr"
        weight           = 2
        [languages.fr.params]
            dateFormat   = "2. January 2006"
            timeFormat   = "HH:mm"                 # https://momentjs.com/docs/#/displaying/format/
            description  = "Site web personnel de Jacques Supcik"
            footerText   = ""

