[build]
publish = "public"
command = "make build"

[build.environment]
HUGO_VERSION = "0.57.2"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "make deploy-preview"

[context.branch-deploy]
command = "make branch-deploy"
