version: 2

checkout:
  post:
    - 
    - git submodule update --init

jobs:
   build:
     docker:
       - image: supcik/my-site-builder
     steps:
       - checkout
       - run: git submodule sync
       - run: git submodule update --init
       - run: hugo
       - run: tar czvf supcik_net.tgz -C public .
       - store_artifacts:
           path: supcik_net.tgz
           destination: supcik_net.tgz
