defaults: &defaults
    docker:
        - image: supcik/my-site-builder

version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: hugo
            - run: tar czvf supcik_net.tgz -C public .
            - store_artifacts:
                path: supcik_net.tgz
                destination: supcik_net.tgz


    deploy:
        <<: *defaults
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: hugo
            - run: mkdir dist
            - run: tar czvf dist/supcik_net.tgz -C public .
            - run: |
                ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME \
                    -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` dist/

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master

